<?php

namespace BibliotecaBundle\Repository;

/**
 * AcervosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcervosRepository extends \Doctrine\ORM\EntityRepository
{
}
